//! # AST Type Generation
//!
//! Base traits and utilities for typed AST wrappers around Red tree nodes.
//!
//! This module provides the foundation for generating typed AST wrappers that allow
//! users to write `expr.lhs()` instead of manual node traversal.
//!
//! ## Usage
//!
//! ```rust,no_run
//! use sipha::syntax::{SyntaxNode, SyntaxKind};
//!
//! // Typed AST wrapper (generated by procedural macro)
//! pub struct ExprNode {
//!     node: SyntaxNode<MySyntaxKind>,
//! }
//!
//! impl ExprNode {
//!     pub fn new(node: SyntaxNode<MySyntaxKind>) -> Self {
//!         Self { node }
//!     }
//!
//!     pub fn lhs(&self) -> Option<SyntaxNode<MySyntaxKind>> {
//!         // Generated based on grammar labels
//!         self.node.children().find(|n| /* label check */)
//!     }
//! }
//! ```

use crate::syntax::{SyntaxKind, SyntaxNode};

/// Base trait for typed AST nodes
///
/// This trait is implemented by generated AST wrapper types to provide
/// a common interface for typed node access.
pub trait AstNode<K: SyntaxKind> {
    /// Get the underlying syntax node
    fn syntax_node(&self) -> &SyntaxNode<K>;

    /// Get the kind of this node
    fn kind(&self) -> K {
        self.syntax_node().kind()
    }

    /// Get the text range of this node
    fn text_range(&self) -> crate::syntax::TextRange {
        self.syntax_node().text_range()
    }

    /// Get the text content of this node
    fn text(&self) -> String {
        self.syntax_node().text()
    }
}

/// Helper trait for converting `SyntaxNode` to typed AST nodes
pub trait FromSyntaxNode<K: SyntaxKind> {
    /// The typed AST node type
    type NodeType: AstNode<K>;

    /// Try to convert a `SyntaxNode` to a typed AST node
    fn from_syntax_node(node: SyntaxNode<K>) -> Option<Self::NodeType>;
}
